AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Disable some overly strict cops for a legacy codebase
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*'

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
